
---
format:
  html: {toc: true, toc-depth: 4, theme: spacelab, output-file: visualize_data.html}
highlight-style: nord
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style>
<script src="visualize_data_files/md-default4.js" type="text/javascript"></script><script src="visualize_data_files/md-default5.js" type="text/javascript"></script><script src="visualize_data_files/vega6.js" type="text/javascript"></script><script src="visualize_data_files/vega7.js" type="text/javascript"></script><script src="visualize_data_files/vega8.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns visualize-data
  (:require
    [aerial.hanami.templates :as ht]
    [generate-data :refer [data]]
    [nextjournal.clerk :as clerk]
    [scicloj.clay.v2.api :as clay]
    [scicloj.kind-clerk.api :as kind-clerk]
    [scicloj.ml.dataset :as ds]
    [scicloj.noj.v1.vis.hanami :as hanami]))
```
:::



::: {.sourceClojure}
```clojure
(kind-clerk/setup!)
```
:::



::: {.printedClojure}
```clojure
:ok

```
:::



# Visualize Data


::: {.sourceClojure}
```clojure
(comment
  (clerk/serve! {:browse? true :watch-paths ["."]})
  (clerk/show! "src/assignment/generate_data.clj")
  (clerk/build! {:paths ["notebooks/visualize_data.clj"]}))
```
:::



::: {.sourceClojure}
```clojure
(ds/head data)
```
:::


_unnamed [5 3]:

|        :x1 |         :x2 | :group |
|-----------:|------------:|--------|
| 1.93704668 |  8.32009995 |  gamma |
| 5.82493513 |  7.76927176 |  gamma |
| 5.39182984 | 10.58551181 |  gamma |
| 9.19427502 |  7.03201886 |  gamma |
| 7.91315598 |  4.16772485 |  gamma |




::: {.sourceClojure}
```clojure
(ds/info data)
```
:::


_unnamed: descriptive-stats [3 12]:

| :col-name | :datatype | :n-valid | :n-missing |         :min |      :mean | :mode |        :max | :standard-deviation |       :skew | :first |      :last |
|-----------|-----------|---------:|-----------:|-------------:|-----------:|-------|------------:|--------------------:|------------:|--------|------------|
|       :x1 |  :float64 |      600 |          0 |  -4.59248552 | 3.42852834 |       | 11.72362278 |          3.76698776 | -0.15311702 |  1.937 |    -0.7329 |
|       :x2 |  :float64 |      600 |          0 | -16.48889331 | 3.38855586 |       | 23.00009878 |          6.08113998 | -0.35337515 |  8.320 |      8.987 |
|    :group |   :string |      600 |          0 |              |            | gamma |             |                     |             |  gamma | log-normal |




::: {.sourceClojure}
```clojure
(defn dist-range [dist]
  (-> (apply max dist)
      (-
        (apply min dist))))
```
:::



::: {.sourceClojure}
```clojure
(-> (ds/select-rows data #(= (:group %) "normal"))
    (hanami/histogram :x2 {:nbins 20}))
```
:::


<div style="max-height:600px;overflow-y:auto;"><div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"field":"count","type":"quantitative"},"x":{"scale":{"zero":false},"field":"left","type":"quantitative","title":"x2"},"y2":{"field":0,"type":"quantitative"},"x2":{"scale":{"zero":false},"field":"right","type":"quantitative"}},"mark":"rect","width":400,"background":"floralwhite","height":300,"data":{"url":"visualize_data_files\/0.csv","format":{"type":"csv"}}});</script></div></div>


::: {.sourceClojure}
```clojure
(-> (:x2 (ds/select-rows data #(= (:group %) "normal")))
    dist-range)
```
:::



::: {.printedClojure}
```clojure
23.37639061361745

```
:::



::: {.sourceClojure}
```clojure
(-> (ds/select-rows data #(= (:group %) "gamma"))
    (hanami/histogram :x2 {:nbins 20}))
```
:::


<div style="max-height:600px;overflow-y:auto;"><div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"field":"count","type":"quantitative"},"x":{"scale":{"zero":false},"field":"left","type":"quantitative","title":"x2"},"y2":{"field":0,"type":"quantitative"},"x2":{"scale":{"zero":false},"field":"right","type":"quantitative"}},"mark":"rect","width":400,"background":"floralwhite","height":300,"data":{"url":"visualize_data_files\/1.csv","format":{"type":"csv"}}});</script></div></div>


::: {.sourceClojure}
```clojure
(-> (:x2 (ds/select-rows data #(= (:group %) "gamma")))
    dist-range)
```
:::



::: {.printedClojure}
```clojure
21.19513048307295

```
:::



::: {.sourceClojure}
```clojure
(-> (ds/select-rows data #(= (:group %) "log-normal"))
    (hanami/histogram :x2 {:nbins 20}))
```
:::


<div style="max-height:600px;overflow-y:auto;"><div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"field":"count","type":"quantitative"},"x":{"scale":{"zero":false},"field":"left","type":"quantitative","title":"x2"},"y2":{"field":0,"type":"quantitative"},"x2":{"scale":{"zero":false},"field":"right","type":"quantitative"}},"mark":"rect","width":400,"background":"floralwhite","height":300,"data":{"url":"visualize_data_files\/2.csv","format":{"type":"csv"}}});</script></div></div>


::: {.sourceClojure}
```clojure
(-> (:x2 (ds/select-rows data #(= (:group %) "log-normal")))
    dist-range)
```
:::



::: {.printedClojure}
```clojure
18.245427592279636

```
:::


Scatter plot


::: {.sourceClojure}
```clojure
(-> data
    (hanami/plot ht/point-chart
                 {:X "x1" :Y "x2" :COLOR "group"}))
```
:::


<div style="max-height:600px;overflow-y:auto;"><div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"field":"x2","type":"quantitative"},"color":{"field":"group","type":"nominal"},"x":{"field":"x1","type":"quantitative"}},"mark":{"type":"circle","tooltip":true},"width":400,"background":"floralwhite","height":300,"data":{"url":"visualize_data_files\/3.csv","format":{"type":"csv"}}});</script></div></div>


::: {.sourceClojure}
```clojure
(comment
  (clay/make! {:format      [:quarto :html]
               :source-path "notebooks/visualize_data.clj"
               :quarto      {:highlight-style :nord}}))
```
:::


<div style="background-color:grey;height:2px;width:100%;"></div>

<div><pre><small><small>source: notebooks/visualize_data.clj</small></small></pre></div>